/**
 * Project NETRA — Kafka Topic Definitions
 * Event-driven architecture for clip processing, alerts, and audit.
 */

// ──────────────────────────────────────────────────────────────
// TOPIC DEFINITIONS
// ──────────────────────────────────────────────────────────────

export const KAFKA_TOPICS = {
  // Raw clip upload from Bridge Agent → ingestion service
  CLIPS_RAW: 'netra.clips.raw',

  // Processed clips (after virus scan + hash verification)
  CLIPS_PROCESSED: 'netra.clips.processed',

  // Event records (metadata created after clip ingestion)
  EVENTS: 'netra.events',

  // Analytics job requests (fan-out to AI services)
  ANALYTICS_JOBS: 'netra.analytics.jobs',

  // Analytics results from AI services
  ANALYTICS_RESULTS: 'netra.analytics.results',

  // ANPR specific
  ANPR_JOBS: 'netra.anpr.jobs',
  ANPR_RESULTS: 'netra.anpr.results',

  // Face recognition
  FR_JOBS: 'netra.fr.jobs',
  FR_RESULTS: 'netra.fr.results',

  // Re-ID
  REID_JOBS: 'netra.reid.jobs',
  REID_RESULTS: 'netra.reid.results',

  // Audio analysis
  AUDIO_JOBS: 'netra.audio.jobs',
  AUDIO_RESULTS: 'netra.audio.results',

  // Behavior analysis
  BEHAVIOR_JOBS: 'netra.behavior.jobs',
  BEHAVIOR_RESULTS: 'netra.behavior.results',

  // Alerts (generated by analytics or rule engine)
  ALERTS: 'netra.alerts',

  // Alert actions (acknowledge, attest, dismiss)
  ALERT_ACTIONS: 'netra.alerts.actions',

  // Consent state changes (critical — revocation propagation)
  CONSENT_CHANGES: 'netra.consent.changes',

  // Camera state updates
  CAMERA_STATE: 'netra.camera.state',

  // Live pull commands and status
  LIVE_PULL_COMMANDS: 'netra.live_pull.commands',
  LIVE_PULL_STATUS: 'netra.live_pull.status',

  // Watchlist changes
  WATCHLIST_CHANGES: 'netra.watchlist.changes',

  // Audit events (append-only)
  AUDIT: 'netra.audit',

  // Notifications
  NOTIFICATIONS: 'netra.notifications',

  // Dead letter queues (failed message routing)
  DLQ_ANALYTICS: 'netra.dlq.analytics',
  DLQ_ALERTS: 'netra.dlq.alerts',
  DLQ_AUDIT: 'netra.dlq.audit',
} as const;

export type KafkaTopic = typeof KAFKA_TOPICS[keyof typeof KAFKA_TOPICS];

// ──────────────────────────────────────────────────────────────
// PARTITION STRATEGY
// ──────────────────────────────────────────────────────────────

/**
 * Partition counts chosen for:
 * - Clips: camera_id partitioning ensures ordering per camera
 * - Events: same as clips
 * - Analytics: high throughput, many partitions for parallelism
 * - Audit: single partition for strict ordering of hash chain
 * - Consent: camera_id partitioning for ordered state machine
 */
export const TOPIC_CONFIG: Record<string, { partitions: number; replicationFactor: number; retentionMs: number }> = {
  [KAFKA_TOPICS.CLIPS_RAW]:          { partitions: 12, replicationFactor: 3, retentionMs: 86400000 },    // 1 day
  [KAFKA_TOPICS.CLIPS_PROCESSED]:    { partitions: 12, replicationFactor: 3, retentionMs: 86400000 },
  [KAFKA_TOPICS.EVENTS]:             { partitions: 12, replicationFactor: 3, retentionMs: 604800000 },   // 7 days
  [KAFKA_TOPICS.ANALYTICS_JOBS]:     { partitions: 24, replicationFactor: 3, retentionMs: 3600000 },     // 1 hour
  [KAFKA_TOPICS.ANALYTICS_RESULTS]:  { partitions: 24, replicationFactor: 3, retentionMs: 3600000 },
  [KAFKA_TOPICS.ANPR_JOBS]:          { partitions: 8,  replicationFactor: 3, retentionMs: 3600000 },
  [KAFKA_TOPICS.ANPR_RESULTS]:       { partitions: 8,  replicationFactor: 3, retentionMs: 3600000 },
  [KAFKA_TOPICS.FR_JOBS]:            { partitions: 8,  replicationFactor: 3, retentionMs: 3600000 },
  [KAFKA_TOPICS.FR_RESULTS]:         { partitions: 8,  replicationFactor: 3, retentionMs: 3600000 },
  [KAFKA_TOPICS.REID_JOBS]:          { partitions: 4,  replicationFactor: 3, retentionMs: 3600000 },
  [KAFKA_TOPICS.REID_RESULTS]:       { partitions: 4,  replicationFactor: 3, retentionMs: 3600000 },
  [KAFKA_TOPICS.AUDIO_JOBS]:         { partitions: 8,  replicationFactor: 3, retentionMs: 3600000 },
  [KAFKA_TOPICS.AUDIO_RESULTS]:      { partitions: 8,  replicationFactor: 3, retentionMs: 3600000 },
  [KAFKA_TOPICS.ALERTS]:             { partitions: 6,  replicationFactor: 3, retentionMs: 604800000 },
  [KAFKA_TOPICS.ALERT_ACTIONS]:      { partitions: 6,  replicationFactor: 3, retentionMs: 604800000 },
  [KAFKA_TOPICS.CONSENT_CHANGES]:    { partitions: 12, replicationFactor: 3, retentionMs: 86400000 },    // camera_id partitioned
  [KAFKA_TOPICS.CAMERA_STATE]:       { partitions: 12, replicationFactor: 3, retentionMs: 86400000 },
  [KAFKA_TOPICS.LIVE_PULL_COMMANDS]: { partitions: 4,  replicationFactor: 3, retentionMs: 3600000 },
  [KAFKA_TOPICS.LIVE_PULL_STATUS]:   { partitions: 4,  replicationFactor: 3, retentionMs: 3600000 },
  [KAFKA_TOPICS.WATCHLIST_CHANGES]:  { partitions: 2,  replicationFactor: 3, retentionMs: 604800000 },
  [KAFKA_TOPICS.AUDIT]:              { partitions: 1,  replicationFactor: 3, retentionMs: -1 },           // infinite retention, single partition for ordering
  [KAFKA_TOPICS.NOTIFICATIONS]:      { partitions: 6,  replicationFactor: 3, retentionMs: 86400000 },
  [KAFKA_TOPICS.DLQ_ANALYTICS]:      { partitions: 3,  replicationFactor: 3, retentionMs: 604800000 },
  [KAFKA_TOPICS.DLQ_ALERTS]:         { partitions: 3,  replicationFactor: 3, retentionMs: 604800000 },
  [KAFKA_TOPICS.DLQ_AUDIT]:          { partitions: 1,  replicationFactor: 3, retentionMs: -1 },
};

// ──────────────────────────────────────────────────────────────
// MESSAGE SCHEMAS
// ──────────────────────────────────────────────────────────────

export interface ClipUploadedMessage {
  eventId: string;
  cameraId: string;         // pseudonymous
  eventType: string;
  occurredAt: string;       // ISO 8601
  clipPath: string;         // MinIO path
  clipHash: string;         // SHA-256
  clipSignature: string;    // Bridge Agent signature
  clipSizeBytes: number;
  clipDurationMs: number;
  geoPoint?: { lat: number; lng: number };
  triggerConfidence: number;
  edgeDetections: DetectionResult[];
  agentVersion: string;
  uploadedAt: string;
}

export interface DetectionResult {
  class: string;
  confidence: number;
  bbox: [number, number, number, number];
}

export interface AnalyticsJobMessage {
  jobId: string;
  eventId: string;
  clipPath: string;
  clipHash: string;
  jobTypes: ('ANPR' | 'FACE_DETECTION' | 'FACE_RECOGNITION' | 'PERSON_REID' | 'VEHICLE_REID' | 'AUDIO' | 'BEHAVIOR')[];
  investigationId?: string;   // if scoped search
  watchlistActive: boolean;
  createdAt: string;
}

export interface AnalyticsResultMessage {
  jobId: string;
  eventId: string;
  jobType: string;
  success: boolean;
  results: Record<string, any>;
  processingTimeMs: number;
  modelVersion: string;
  completedAt: string;
  error?: string;
}

export interface AlertMessage {
  alertId: string;
  cameraId: string;
  eventId?: string;
  alertType: string;
  title: string;
  description?: string;
  confidence: number;
  geoPoint?: { lat: number; lng: number };
  notifyCitizen: boolean;
  notifyPcr: boolean;
  matchCandidates?: any[];  // For FR/ANPR matches — top-N only
  createdAt: string;
}

export interface ConsentChangeMessage {
  cameraId: string;
  citizenId: string;        // pseudonymous
  changeType: 'REVOKED' | 'PAUSED' | 'RESUMED' | 'CONSENT_UPDATED' | 'PRIVACY_ZONES_UPDATED';
  newState?: Record<string, any>;
  timestamp: string;
  propagationDeadline: string;  // must reach Bridge Agent by this time (≤60s)
}

export interface AuditMessage {
  logUuid: string;
  action: string;
  actorId?: string;
  actorRole?: string;
  subjectType?: string;
  subjectId?: string;
  investigationId?: string;
  caseReference?: string;
  details: Record<string, any>;
  eventHash: string;
  prevHash: string;
  occurredAt: string;
}

// ──────────────────────────────────────────────────────────────
// CONSUMER GROUP DEFINITIONS
// ──────────────────────────────────────────────────────────────

export const CONSUMER_GROUPS = {
  INGESTION:      'netra-ingestion-cg',
  ANALYTICS_ORCH: 'netra-analytics-orchestrator-cg',
  ANPR_WORKER:    'netra-anpr-worker-cg',
  FR_WORKER:      'netra-fr-worker-cg',
  REID_WORKER:    'netra-reid-worker-cg',
  AUDIO_WORKER:   'netra-audio-worker-cg',
  BEHAVIOR_WORKER:'netra-behavior-worker-cg',
  ALERT_ENGINE:   'netra-alert-engine-cg',
  NOTIFICATION:   'netra-notification-cg',
  AUDIT_WRITER:   'netra-audit-writer-cg',
  CONSENT_PROP:   'netra-consent-propagator-cg',
  BRIDGE_AGENT:   'netra-bridge-agent-cg',
} as const;
